### ISSUE TITLE
Train script is not working

### ISSUE THREAD

**Issue by Kirmani66** [taipingeric/yolo-v4-tf.keras#11]
It is giving nonetype error

InvalidArgumentError:  TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 961, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 837, in wrapped_generator
    for data in generator_fn():

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 963, in generator_fn
    yield x[i]

  File "../utils.py", line 159, in __getitem__
    X, y_tensor, y_bbox = self.__data_generation(lines)

  File "../utils.py", line 179, in __data_generation
    img_data, box_data = self.get_data(line)

  File "../utils.py", line 190, in get_data
    img = cv2.imread(os.path.join(self.folder_path, img_path))[:, :, ::-1]

TypeError: 'NoneType' object is not subscriptable

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_74263]

Function call stack:
train_function

**Comment by Mahmood-Hussain** [comment]
Did you check your dataset? Are any images missing pre-defined bounding boxes?

**Comment by somesh-kb** [comment]
Facing the same issue. Same error as reported by Kirmani66. Any suggestion to overcome that.
