### ISSUE TITLE
Load Training Checkpoints

### ISSUE THREAD

**Issue by Klimroth** [taipingeric/yolo-v4-tf.keras#18]
The saved model after Training all epochs (model.fit(...) -> model.save_model()) works decently as only the yolo_model seems to be saved. Checkpoints created during training cannot be loaded. 

Tried to write an own Callback but I cannot only save the current version of the yolo_model.

Any suggestions?

-----------------------------------------------

`InvalidArgumentError: Index out of range using input dim 0; input has only 0 dims for '{{node strided_slice_4}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](yolo_loss_1/Identity, strided_slice_4/begin, strided_slice_4/end, strided_slice_4/strides)' with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-8-90592e1f5354>", line 1, in <module>
    model.load_model('/home/omen2/Schreibtisch/OD-Netz_zsm-Tiere/Antilopen_zsm/Training/Kudu_Gelsenkirchen_2-374/Training_nt2/2022-02-07_OD_Kudu_Gelsenkirchen_2-374-ckpt/epoch-225.h5')

  File "/home/omen2/60-PromotionJenny/KI_Projekt/KI-Projekt/global/yolo-v4-tf.keras-master/models.py", line 100, in load_model
    yolov4_output = yolov4_head(self.yolo_model.output, self.num_classes, self.anchors, self.xyscale)

  File "/home/omen2/60-PromotionJenny/KI_Projekt/KI-Projekt/global/yolo-v4-tf.keras-master/custom_layers.py", line 202, in yolov4_head
    bbox0, object_probability0, class_probabilities0, pred_box0 = get_boxes(yolo_neck_outputs[0],

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 973, in _slice_helper
    return strided_slice(

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1140, in strided_slice
    op = gen_array_ops.strided_slice(

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 10174, in strided_slice
    _, _, _op, _outputs = _op_def_library._apply_op_helper(

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 593, in _create_op_internal
    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3319, in _create_op_internal
    ret = Operation(

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1816, in __init__
    self._c_op = _create_c_op(self._graph, node_def, inputs,

  File "/home/omen2/anaconda3/envs/ki/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1657, in _create_c_op
    raise ValueError(str(e))

ValueError: Index out of range using input dim 0; input has only 0 dims for '{{node strided_slice_4}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](yolo_loss_1/Identity, strided_slice_4/begin, strided_slice_4/end, strided_slice_4/strides)' with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.`

**Comment by zohaibjan** [comment]
Have you managed to solve the issue ?. Also how do you load the saved model ?. I am trying to run it outside of jupiter but it fails to load model.

**Comment by shadeofplato** [comment]
@zohaibjan It seems that the issue I am currently experiencing is much the same as the one that you have mentioned. I train a model, and if I run inference with it right away, that is, without saving it, everything works fine. However, if I save the trained model and then load it and try to perform inference, nothing works: the model will be loaded, but it will be completely naive, that is, it will not retain any knowledge that it gained during training.

**Comment by bhorsfield** [comment]
@Klimroth, @shadeofplato, @zohaibjan:  Did anyone ever figure out a solution to this problem?

I am having pretty much the exact same problem that @Klimroth originally reported.  In my case, I trained the model and saved it in SavedModel format.  When I try to load it back in, I get the same error message (see below for details).

The method I am using to load my model as follows:
`model = Yolov4(weight_path=None, class_name_path=class_name_path)`
`model.load_model('./saved_models/my_yolo')`

My system configuration is as follows:

- Ubuntu 18.04
- TensorFlow 2.6.2
- Python 3.6
- HP Omen laptop, NVIDIA GTX1070 GPU, 32GB system memory, 8GB VRAM

---
ValueError: Index out of range using input dim 0; input has only 0 dims for '{{node tf.__operators__.getitem_4/strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](Placeholder, tf.__operators__.getitem_4/strided_slice/stack, tf.__operators__.getitem_4/strided_slice/stack_1, tf.__operators__.getitem_4/strided_slice/stack_2)' with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.

**Comment by bhorsfield** [comment]
@Klimroth, I have created a custom callback that will enable you to load a checkpoint that was created during training.  I also fixed a bug in the `load_model()` method in **models.py** that was contributing to this problem.  

Other changes I have made are as follows:

- Fixed bug in which settings in **config.py** were being ignored when a saved model was loaded from file
- Added `summary()`, `plot_model()` and `layer_list()` methods to **models.py** to enable user to inspect model architecture

Updated versions of **models.py** and **custom_callbacks.py** are attached below:

- [custom_callbacks.py.txt](https://github.com/taipingeric/yolo-v4-tf.keras/files/10894164/custom_callbacks.py.txt)
- [models.py.txt](https://github.com/taipingeric/yolo-v4-tf.keras/files/10894167/models.py.txt)

To load a checkpoint from a previous training run:
`model = Yolov4(weight_path=None, class_name_path=class_name_path)`
`model.load_model('./saved_models/<checkpoint_name>')`

To set up a checkpoint callback and start a new training run:
`mc = ModelCheckpointYolov4('./saved_models/<checkpoint_name>', model_name=model.yolo_model, monitor='val_loss', mode='min', verbose=1, save_best_only=True)`
`model.fit(data_gen_train, initial_epoch=0, epochs=100, val_data_gen=data_gen_val, callbacks=[mc])`
